# Generated by Django 4.2.13 on 2024-06-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aerolinea', models.CharField(max_length=100)),
                ('estatus_sistema', models.BooleanField(default=True, help_text='True si está activo, False si está eliminado.', verbose_name='Estatus en el Sistema')),
            ],
        ),
    ]
