# Generated by Django 4.2.13 on 2024-06-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_aerolinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aeropuerto', models.CharField(max_length=100)),
                ('estatus_sistema', models.BooleanField(default=True, help_text='True si está activo, False si está eliminado.', verbose_name='Estatus en el Sistema')),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus_sistema', models.BooleanField(default=True, help_text='True si está activo, False si está eliminado.', verbose_name='Estatus en el Sistema')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimiento',
            },
        ),
        migrations.AlterModelOptions(
            name='aerolinea',
            options={'verbose_name': 'Aerolinea', 'verbose_name_plural': 'Aerolineas'},
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('estatus_sistema', models.BooleanField(default=True, help_text='True si está activo, False si está eliminado.', verbose_name='Estatus en el Sistema')),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.aerolinea')),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.aeropuerto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.movimiento')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
            },
        ),
    ]
